package com.bpm.fsr.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EvaluateNextBestFlowRuleFact implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "CallAdditionalInfo")
	@org.kie.api.definition.type.Position(value = 2)
	private java.lang.String callAdditionalInfo;

	@org.kie.api.definition.type.Label(value = "isAuthenticated")
	@org.kie.api.definition.type.Position(value = 1)
	private boolean isAuthenticated;

	@org.kie.api.definition.type.Label(value = "IsModemTrained")
	@org.kie.api.definition.type.Position(value = 0)
	private boolean isModemTrained;

	@org.kie.api.definition.type.Label(value = "NextFlowPath")
	@org.kie.api.definition.type.Position(value = 3)
	private java.lang.String nextFlowPath;

	@org.kie.api.definition.type.Label(value = "isPollDSLAMSupported")
	@org.kie.api.definition.type.Position(value = 4)
	private boolean isPollDSLAMSupported;

	public EvaluateNextBestFlowRuleFact() {
	}

	public EvaluateNextBestFlowRuleFact(boolean isModemTrained,
			boolean isAuthenticated, java.lang.String callAdditionalInfo,
			java.lang.String nextFlowPath, boolean isPollDSLAMSupported) {
		this.isModemTrained = isModemTrained;
		this.isAuthenticated = isAuthenticated;
		this.callAdditionalInfo = callAdditionalInfo;
		this.nextFlowPath = nextFlowPath;
		this.isPollDSLAMSupported = isPollDSLAMSupported;
	}

	public boolean isIsPollDSLAMSupported() {
		return this.isPollDSLAMSupported;
	}

	public void setIsPollDSLAMSupported(boolean isPollDSLAMSupported) {
		this.isPollDSLAMSupported = isPollDSLAMSupported;
	}

	public java.lang.String getCallAdditionalInfo() {
		return this.callAdditionalInfo;
	}

	public void setCallAdditionalInfo(java.lang.String callAdditionalInfo) {
		this.callAdditionalInfo = callAdditionalInfo;
	}

	public boolean isIsAuthenticated() {
		return this.isAuthenticated;
	}

	public void setIsAuthenticated(boolean isAuthenticated) {
		this.isAuthenticated = isAuthenticated;
	}

	public boolean isIsModemTrained() {
		return this.isModemTrained;
	}

	public void setIsModemTrained(boolean isModemTrained) {
		this.isModemTrained = isModemTrained;
	}

	public java.lang.String getNextFlowPath() {
		return this.nextFlowPath;
	}

	public void setNextFlowPath(java.lang.String nextFlowPath) {
		this.nextFlowPath = nextFlowPath;
	}

	@Override
	public String toString() {
		return "EvaluateNextBestFlowRuleFact [callAdditionalInfo="
				+ callAdditionalInfo + ", isAuthenticated=" + isAuthenticated
				+ ", isModemTrained=" + isModemTrained + ", nextFlowPath="
				+ nextFlowPath + ", isPollDSLAMSupported="
				+ isPollDSLAMSupported + "]";
	}

}