package com.bpm.fsr.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IPVerificationRuleFact implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Wan IP")
	@org.kie.api.definition.type.Position(value = 2)
	private java.lang.String authenticationWanIP;

	@org.kie.api.definition.type.Label(value = "IPQuantity")
	@org.kie.api.definition.type.Position(value = 1)
	private int iPQuantity;

	@org.kie.api.definition.type.Label(value = "IP Range Matches")
	@org.kie.api.definition.type.Position(value = 3)
	private java.lang.String ipRangeMatches;

	@org.kie.api.definition.type.Label(value = "WanIPIpmsIPMatch")
	@org.kie.api.definition.type.Position(value = 0)
	private boolean wanIPIpmsIPMatch;

	public IPVerificationRuleFact() {
	}

	public IPVerificationRuleFact(boolean wanIPIpmsIPMatch, int iPQuantity,
			java.lang.String authenticationWanIP,
			java.lang.String ipRangeMatches) {
		this.wanIPIpmsIPMatch = wanIPIpmsIPMatch;
		this.iPQuantity = iPQuantity;
		this.authenticationWanIP = authenticationWanIP;
		this.ipRangeMatches = ipRangeMatches;
	}

	public java.lang.String getAuthenticationWanIP() {
		return this.authenticationWanIP;
	}

	public void setAuthenticationWanIP(java.lang.String authenticationWanIP) {
		this.authenticationWanIP = authenticationWanIP;
	}

	public int getiPQuantity() {
		return this.iPQuantity;
	}

	public void setiPQuantity(int iPQuantity) {
		this.iPQuantity = iPQuantity;
	}

	public java.lang.String getIpRangeMatches() {
		return this.ipRangeMatches;
	}

	public void setIpRangeMatches(java.lang.String ipRangeMatches) {
		this.ipRangeMatches = ipRangeMatches;
	}

	public boolean isWanIPIpmsIPMatch() {
		return this.wanIPIpmsIPMatch;
	}

	public void setWanIPIpmsIPMatch(boolean wanIPIpmsIPMatch) {
		this.wanIPIpmsIPMatch = wanIPIpmsIPMatch;
	}

	@Override
	public String toString() {
		return "IPVerificationRuleFact [authenticationWanIP="
				+ authenticationWanIP + ", iPQuantity=" + iPQuantity
				+ ", ipRangeMatches=" + ipRangeMatches + ", wanIPIpmsIPMatch="
				+ wanIPIpmsIPMatch + "]";
	}

}