package com.bpm.fsr.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ModemProtocolRuleFact implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("BBCOSEndsInZ")
	@org.kie.api.definition.type.Position(3)
	private boolean bbcosEndsInZ;

	@org.kie.api.definition.type.Label("BBCOS present")
	@org.kie.api.definition.type.Position(12)
	private boolean bbcosPresent;

	@org.kie.api.definition.type.Label("ICL IP Qty")
	@org.kie.api.definition.type.Position(5)
	private int iclIPQty;

	@org.kie.api.definition.type.Label("Protocol")
	@org.kie.api.definition.type.Position(1)
	private java.lang.String protocol;

	@org.kie.api.definition.type.Label("IMPROV Static IP Present")
	@org.kie.api.definition.type.Position(6)
	private boolean improvStaticIPPresent;

	@org.kie.api.definition.type.Label("MARTENS Static IP present")
	@org.kie.api.definition.type.Position(4)
	private boolean martensStaticIPpresent;

	@org.kie.api.definition.type.Label("Prism On Account")
	@org.kie.api.definition.type.Position(2)
	private boolean prismOnAccount;

	@org.kie.api.definition.type.Label(value = "Legacy market")
	@org.kie.api.definition.type.Position(value = 7)
	private java.lang.String legacyMarket;

	@org.kie.api.definition.type.Label(value = "L-ENS L-EQ True SIP")
	@org.kie.api.definition.type.Position(value = 8)
	private boolean lENSTrueSip;

	@org.kie.api.definition.type.Label(value = "L-ENS PPPoE")
	@org.kie.api.definition.type.Position(value = 9)
	private boolean lENSPPPoE;

	@org.kie.api.definition.type.Label(value = "L-CRIS PPPoE")
	@org.kie.api.definition.type.Position(value = 10)
	private boolean lCRISPPPoE;

	@org.kie.api.definition.type.Label(value = "IPoE (DHCP)")
	@org.kie.api.definition.type.Position(value = 11)
	private boolean iPoE;
	
	//@org.kie.api.definition.type.Label("MadisonRiver Customer")
	//@org.kie.api.definition.type.Position(13)
	//private boolean madisonRiverCustomer;
	


	

/*	public boolean getMadisonRiverCustomer() {
		return this.madisonRiverCustomer;
	}

	public void setMadisonRiverCustomer(boolean madisonRiverCustomer) {
		this.madisonRiverCustomer = madisonRiverCustomer;
	}*/

	public boolean getBbcosEndsInZ() {
		return this.bbcosEndsInZ;
	}

	public void setBbcosEndsInZ(boolean bbcosEndsInZ) {
		this.bbcosEndsInZ = bbcosEndsInZ;
	}

	public boolean getBbcosPresent() {
		return this.bbcosPresent;
	}

	public void setBbcosPresent(boolean bbcosPresent) {
		this.bbcosPresent = bbcosPresent;
	}

	public int getIclIPQty() {
		return this.iclIPQty;
	}

	public void setIclIPQty(int iclIPQty) {
		this.iclIPQty = iclIPQty;
	}

	public java.lang.String getProtocol() {
		return this.protocol;
	}

	public void setProtocol(java.lang.String protocol) {
		this.protocol = protocol;
	}

	public boolean getImprovStaticIPPresent() {
		return this.improvStaticIPPresent;
	}

	public void setImprovStaticIPPresent(boolean improvStaticIPPresent) {
		this.improvStaticIPPresent = improvStaticIPPresent;
	}

	public boolean getMartensStaticIPpresent() {
		return this.martensStaticIPpresent;
	}

	public void setMartensStaticIPpresent(boolean martensStaticIPpresent) {
		this.martensStaticIPpresent = martensStaticIPpresent;
	}

	public boolean getPrismOnAccount() {
		return this.prismOnAccount;
	}

	public void setPrismOnAccount(boolean prismOnAccount) {
		this.prismOnAccount = prismOnAccount;
	}

	public java.lang.String getLegacyMarket() {
		return this.legacyMarket;
	}

	public void setLegacyMarket(java.lang.String legacyMarket) {
		this.legacyMarket = legacyMarket;
	}

	public boolean getlENSTrueSip() {
		return this.lENSTrueSip;
	}

	public void setlENSTrueSip(boolean lENSTrueSip) {
		this.lENSTrueSip = lENSTrueSip;
	}

	public boolean getlENSPPPoE() {
		return this.lENSPPPoE;
	}

	public void setlENSPPPoE(boolean lENSPPPoE) {
		this.lENSPPPoE = lENSPPPoE;
	}

	public boolean getlCRISPPPoE() {
		return this.lCRISPPPoE;
	}

	public void setlCRISPPPoE(boolean lCRISPPPoE) {
		this.lCRISPPPoE = lCRISPPPoE;
	}

	public boolean getiPoE() {
		return this.iPoE;
	}

	public void setiPoE(boolean iPoE) {
		this.iPoE = iPoE;
	}

	public ModemProtocolRuleFact() {
	}

	public ModemProtocolRuleFact(boolean bbcosPresent,
			java.lang.String iclProtocol, boolean prismOnAccount,
			boolean bbcosEndsInZ, boolean martensStaticIPpresent, int iclIPQty,
			boolean improvStaticIPPresent, java.lang.String legacyMarket,
			boolean lENSTrueSip, boolean lENSPPPoE, boolean lCRISPPPoE,
			boolean iPoE) {
		//this.madisonRiverCustomer = madisonRiverCustomer;
		this.bbcosPresent = bbcosPresent;
		this.protocol = iclProtocol;
		this.prismOnAccount = prismOnAccount;
		this.bbcosEndsInZ = bbcosEndsInZ;
		this.martensStaticIPpresent = martensStaticIPpresent;
		this.iclIPQty = iclIPQty;
		this.improvStaticIPPresent = improvStaticIPPresent;
		this.legacyMarket = legacyMarket;
		this.lENSTrueSip = lENSTrueSip;
		this.lENSPPPoE = lENSPPPoE;
		this.lCRISPPPoE = lCRISPPPoE;
		this.iPoE = iPoE;
		
	}

	@Override
	public String toString() {
		return "ModemProtocolRuleFact [bbcosEndsInZ=" + bbcosEndsInZ
				+",  bbcosPresent=" + bbcosPresent + ", iclIPQty=" + iclIPQty
				+ ", protocol=" + protocol + ", improvStaticIPPresent="
				+ improvStaticIPPresent + ", martensStaticIPpresent="
				+ martensStaticIPpresent + ", prismOnAccount=" + prismOnAccount
				+ ", legacyMarket=" + legacyMarket + ", lENSTrueSip="
				+ lENSTrueSip + ", lENSPPPoE=" + lENSPPPoE + ", lCRISPPPoE="
				+ lCRISPPPoE + ", iPoE=" + iPoE +"]";
	}

}