package com.bpm.fsr.model;

/**
 * This class was automatically generated by the data modeler tool..
 */

@org.kie.api.definition.type.Label("ticketingNodeRuleFact")
public class TicketingNodeRuleFact implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("endTaskId")
	@org.kie.api.definition.type.Position(5)
	private java.lang.String endTaskId;

    @org.kie.api.definition.type.Label("flowName")
	@org.kie.api.definition.type.Position(0)
	private java.lang.String flowName;

    @org.kie.api.definition.type.Label("legacy")
	@org.kie.api.definition.type.Position(1)
	private java.lang.String legacy;

    @org.kie.api.definition.type.Label("originatingFlow")
	@org.kie.api.definition.type.Position(4)
	private java.lang.String originatingFlow;

    @org.kie.api.definition.type.Label("poc")
	@org.kie.api.definition.type.Position(2)
	private java.lang.String poc;

    @org.kie.api.definition.type.Label("prismOnAccount")
	@org.kie.api.definition.type.Position(3)
	private Boolean prismOnAccount;

    @org.kie.api.definition.type.Label("node0")
	@org.kie.api.definition.type.Position(6)
	private java.lang.String node0;

	@org.kie.api.definition.type.Label("node1")
	@org.kie.api.definition.type.Position(7)
	private java.lang.String node1;

	@org.kie.api.definition.type.Label("node2")
	@org.kie.api.definition.type.Position(8)
	private java.lang.String node2;

	@org.kie.api.definition.type.Label("node3")
	@org.kie.api.definition.type.Position(9)
	private java.lang.String node3;

	@org.kie.api.definition.type.Label("node4")
	@org.kie.api.definition.type.Position(10)
	private java.lang.String node4;

	@org.kie.api.definition.type.Label("node5")
	@org.kie.api.definition.type.Position(11)
	private java.lang.String node5;

	@org.kie.api.definition.type.Label("notes")
	@org.kie.api.definition.type.Position(12)
	private java.lang.String notes;

	@org.kie.api.definition.type.Label(value = "accessTech")
	@org.kie.api.definition.type.Position(value = 13)
	private java.lang.String accessTech;
	
	@org.kie.api.definition.type.Label("keyFinding")
	@org.kie.api.definition.type.Position(14)
	private java.lang.String keyFinding;

	public java.lang.String getFlowName() {
        return this.flowName;
    }
    
    public void setFlowName(java.lang.String flowName) {
        this.flowName = flowName;
    }

    public java.lang.String getLegacy() {
        return this.legacy;
    }
    
    public void setLegacy(java.lang.String legacy) {
        this.legacy = legacy;
    }

    public java.lang.String getOriginatingFlow() {
        return this.originatingFlow;
    }
    
    public void setOriginatingFlow(java.lang.String originatingFlow) {
        this.originatingFlow = originatingFlow;
    }

    public java.lang.String getPoc() {
        return this.poc;
    }
    
    public void setPoc(java.lang.String poc) {
        this.poc = poc;
    }

    public java.lang.String getNode0() {
		return this.node0;
	}

	public void setNode0(java.lang.String node0) {
		this.node0 = node0;
	}

	public java.lang.String getNode1() {
		return this.node1;
	}

	public void setNode1(java.lang.String node1) {
		this.node1 = node1;
	}

	public java.lang.String getNode2() {
		return this.node2;
	}

	public void setNode2(java.lang.String node2) {
		this.node2 = node2;
	}

	public java.lang.String getNode3() {
		return this.node3;
	}

	public void setNode3(java.lang.String node3) {
		this.node3 = node3;
	}

	public java.lang.String getNode4() {
		return this.node4;
	}

	public void setNode4(java.lang.String node4) {
		this.node4 = node4;
	}

	public java.lang.String getNode5() {
		return this.node5;
	}

	public void setNode5(java.lang.String node5) {
		this.node5 = node5;
	}

	public java.lang.String getNotes() {
		return this.notes;
	}

	public void setNotes(java.lang.String notes) {
		this.notes = notes;
	}

	public java.lang.String getEndTaskId() {
		return this.endTaskId;
	}

	public void setEndTaskId(java.lang.String endTaskId) {
		this.endTaskId = endTaskId;
	}

	public java.lang.Boolean getPrismOnAccount() {
		return this.prismOnAccount;
	}

	public void setPrismOnAccount(java.lang.Boolean prismOnAccount) {
		this.prismOnAccount = prismOnAccount;
	}

	public java.lang.String getAccessTech() {
		return this.accessTech;
	}

	public void setAccessTech(java.lang.String accessTech) {
		this.accessTech = accessTech;
	}
	
	public java.lang.String getKeyFinding() {
		return this.keyFinding;
	}

	public void setKeyFinding(java.lang.String keyFinding) {
		this.keyFinding = keyFinding;
	}

	public TicketingNodeRuleFact() {
	}

	public TicketingNodeRuleFact(java.lang.String flowName,
			java.lang.String legacy, java.lang.String poc,
			java.lang.Boolean prismOnAccount, java.lang.String originatingFlow,
			java.lang.String endTaskId, java.lang.String node0,
			java.lang.String node1, java.lang.String node2,
			java.lang.String node3, java.lang.String node4,
			java.lang.String node5, java.lang.String notes,
			java.lang.String accessTech, java.lang.String keyFinding) {
		this.flowName = flowName;
		this.legacy = legacy;
		this.poc = poc;
		this.prismOnAccount = prismOnAccount;
		this.originatingFlow = originatingFlow;
		this.endTaskId = endTaskId;
		this.node0 = node0;
		this.node1 = node1;
		this.node2 = node2;
		this.node3 = node3;
		this.node4 = node4;
		this.node5 = node5;
		this.notes = notes;
		this.accessTech = accessTech;
		this.keyFinding = keyFinding;
	}
	
	@Override
	public String toString() {
		return "TicketingNodeRuleFact [endTaskId=" + endTaskId + ", flowName="
				+ flowName + ", legacy=" + legacy + ", originatingFlow="
				+ originatingFlow + ", poc=" + poc + ", prismOnAccount="
				+ prismOnAccount + ", node0=" + node0 + ", node1=" + node1
				+ ", node2=" + node2 + ", node3=" + node3 + ", node4=" + node4
				+ ", node5=" + node5 + ", notes=" + notes + ", accessTech="
				+ accessTech + ", keyFinding=" + keyFinding + "]";
	}

}